### PR TITLE
python2 compatible fix

### PR DESCRIPTION
**Pull request by atten**

### CODE REVIEW

**Comment by blag** [comment]
Submit this to upstream and I'll merge it in (I'm an upstream maintainer).

**Comment by atten** [comment]
You mean goinnn/django-multiselectfield ?
I've tried to make Pull Request into it, but it has conflict. My commit could be applied just to current fork.

**Comment by blag** [comment]
If I just applied your PR into my repo it wouldn't make it into PyPI.

But don't worry about it, I'll pull your changes into upstream for you since I'm already adding Django 1.11 and Python 3.6 to the test matrix. Please submit any future PRs to upstream directly though.

Thanks for your contribution!

**Comment by blag** [comment]
Released in version 0.1.6 on PyPI.

Note that the 0.1.6dev1 (released a bit ago) and the 0.1.6dev2 (also released today) do *not* have your fix in them.

**Pull request closed without merging**
